package com.backend.gapfinder.enums;

public enum NotificationTypeEnum {
    MATCH_REQUEST,
    MATCH_ACCEPTED,
    MATCH_REJECTED,
    MATCH_CLOSED,
    MESSAGE_RECEIVED,
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    OPEN_TABLE_JOIN,
    GROUP_GAP_AVAILABLE,
    GAP_STARTING_SOON,
    GAP_STARTED,
    GAP_ENDING_SOON,
    GAP_ENDED
}